name: delphis_app
description: Chatham application for anonymous discussion

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2

  page_transition: ^1.1.4

  flutter_svg: 0.17.4
  url_launcher: 5.4.5
  random_words: 1.0.2
  image_picker: 0.6.7+2
  file_picker: 1.12.0
  mime: 0.9.6+3
  video_thumbnail: 0.2.2
  transparent_image: 1.0.0
  video_player: 0.10.11+1
  path_provider: 1.6.11
  flutter_cache_manager: 1.4.1
  image: 2.1.13

  flutter_webview_plugin: 0.3.10+1
  provider: ^4.1.3

  intl: 0.16.1
  flutter_secure_storage: 3.3.1+1

  graphql_flutter: 3.0.0
  json_annotation: 3.0.0

  flutter_bloc: 5.0.0
  equatable: 1.2.0

  flutter_segment: 2.0.2
  uuid: 2.0.4

  pull_to_refresh: 1.5.8
  shared_preferences: 0.5.7+3

  uni_links: 0.4.0
  firebase_messaging: ^6.0.16

dev_dependencies:
  # TODO: We need to update image_test_utils to depend on the later version of mockito
  # (^4.0.0) so we can use the newer version of mockito
  mockito: 3.0.2
  lipsum: 1.0.1
  build_runner: ^1.0.0
  json_serializable: 3.2.5
  test: 1.14.7
  image_test_utils: 1.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/anon_face/anon_face.png
    - assets/images/anon_face/1.5x/anon_face.png
    - assets/images/anon_face/2.0x/anon_face.png
    - assets/images/anon_face/4.0x/anon_face.png
    - assets/images/anon_face_transparent/anon_face_transparent.png
    - assets/images/anon_face_transparent/1.5x/anon_face_transparent.png
    - assets/images/anon_face_transparent/2.0x/anon_face_transparent.png
    - assets/images/anon_face_transparent/4.0x/anon_face_transparent.png
    - assets/images/app_icon/image.png
    - assets/images/app_icon/2.0x/image.png
    - assets/images/app_icon/3.0x/image.png
    - assets/images/circle_check_border_trans/image.png
    - assets/images/circle_check_border_trans/1.5x/image.png
    - assets/images/circle_check_border_trans/2.0x/image.png
    - assets/images/circle_check_border_trans/4.0x/image.png
    - assets/images/star_black_border/image.png
    - assets/images/star_black_border/1.5x/image.png
    - assets/images/star_black_border/2.0x/image.png
    - assets/images/star_black_border/3.0x/image.png
    - assets/images/star_white_border/image.png
    - assets/images/star_white_border/1.5x/image.png
    - assets/images/star_white_border/2.0x/image.png
    - assets/images/star_white_border/3.0x/image.png
    - assets/images/star_bolt_purple/image.png
    - assets/images/star_bolt_purple/1.5x/image.png
    - assets/images/star_bolt_purple/2.0x/image.png
    - assets/images/star_bolt_purple/3.0x/image.png
    - assets/svg/back_chevron.svg
    - assets/svg/chat-icon.svg
    - assets/svg/check_mark.svg
    - assets/svg/forward_chevron.svg
    - assets/svg/paper_airplane.svg
    - assets/svg/twitter_logo_blue.svg
    - assets/svg/twitter_logo_white.svg
    - assets/svg/twitter_logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: NeueHansKendrick
      fonts:
        - asset: fonts/NeueHansKendrick-Thin.ttf
          weight: 100
        - asset: fonts/NeueHansKendrick-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/NeueHansKendrick-ExtraLight.ttf
          weight: 200
        - asset: fonts/NeueHansKendrick-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/NeueHansKendrick-Light.ttf
          weight: 300
        - asset: fonts/NeueHansKendrick-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/NeueHansKendrick-Regular.ttf
          weight: 400
        - asset: fonts/NeueHansKendrick-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/NeueHansKendrick-Medium.ttf
          weight: 500
        - asset: fonts/NeueHansKendrick-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/NeueHansKendrick-SemiBold.ttf
          weight: 600
        - asset: fonts/NeueHansKendrick-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/NeueHansKendrick-Bold.ttf
          weight: 700
        - asset: fonts/NeueHansKendrick-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/NeueHansKendrick-ExtraBold.ttf
          weight: 800
        - asset: fonts/NeueHansKendrick-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/NeueHansKendrick-Heavy.ttf
          weight: 900
        - asset: fonts/NeueHansKendrick-HeavyItalic.ttf
          weight: 900
          style: italic

